# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        suivi_medical_files:
            uri_prefix: /uploads/suivi_medical_files
            upload_destination: '%kernel.project_dir%/public/uploads/suivi_medical_files'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        chirurgie_files:
            uri_prefix: /uploads/chirurgie_files
            upload_destination: '%kernel.project_dir%/public/uploads/chirurgie_files'
            namer: Vich\UploaderBundle\Naming\UniqidNamer